== Demo using JsonSerde from Spring for Apache Kafka

Spring for Apache Kafka provides a convenient `JsonSerde` to be used with Kafka Streams applications.
This sample demonstrates its usage through Spring Cloud Stream.

Clone the repo and build the project:

`./mvnw clean package`

`java -jar target/json-serde-example-0.0.1-SNAPSHOT.jar` (Or run the main app through the IDE)

This sample assumes that you run Kafka broker on localhost:9092. If that is not the case, change the configuration.

Take a look at the `application.yml` for how the `JsonSerde` is used.

The main application contains two processors. A main processor receives data through the input topic and produces the data unchanged to an output topic.
Then there is a test consumer that verifies the data received through the output topic on the main processor.
`JsonSerde` is used as the default Serde. On the inbound side, the conversion is handled by Spring Cloud Stream.

There is also a driver program provided to send data to the input topic on the main processor.
Run the driver program and watch the console on the main processor application.